### ISSUE TITLE
No CSS?

### ISSUE THREAD

**Issue by haylinmoore** [alexcarpenter/material-jekyll-theme#9]
I followed the instructions and keep getting "Failed to load resource: the server responded with a status of 404 (Not Found)"

**Comment by alexcarpenter** [comment]
Can you share a screenshot with the error message?

**Comment by haylinmoore** [comment]
https://hampton.pw/jekyll/ its right here the scss file is not compiling

**Comment by haylinmoore** [comment]
I thinks its because I remove

---
# Only the main Sass file needs front matter (the dashes are enough)
---

from the top because when that is there I then get

nverting 'css/main.scss':
                    Invalid US-ASCII character "\xC2" on line 22
...error:
             Error: Invalid US-ASCII character "\xC2" on line 22
             Error: Run jekyll build --trace for more information.

**Comment by haylinmoore** [comment]
I needed to add 

if locale -a | grep -qF 'C.UTF-8'; then
    loc="C.UTF-8"
else
    loc="en_US.UTF-8"
fi
export LANG=$loc
export LC_ALL=$loc

to my .bashrc
